// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdjtgkgwtsdpfftrrouz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkanRna2d3dHNkcGZmdHJyb3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDI0OTQsImV4cCI6MjA3MjQ3ODQ5NH0.d85iBxp9pl69e3720jEib7DztrBoeIzSXnKAfekjXnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});